// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx2UtltcDM0dP7OrzwKaDYQEterYvrLZA',
    appId: '1:849173214576:web:bbbed22d4ecfa4de874bb5',
    messagingSenderId: '849173214576',
    projectId: 'mymonshaa',
    authDomain: 'mymonshaa.firebaseapp.com',
    storageBucket: 'mymonshaa.appspot.com',
    measurementId: 'G-S0MVT0JXWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw4AXOHgws13ln6epiA_2xA-J5J7kjOmM',
    appId: '1:849173214576:android:84bc40512a3379c7874bb5',
    messagingSenderId: '849173214576',
    projectId: 'mymonshaa',
    storageBucket: 'mymonshaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADvtqlQnKcSIlr_MK78dFS1QBEZS25dZ4',
    appId: '1:849173214576:ios:8aed0c75fe91593b874bb5',
    messagingSenderId: '849173214576',
    projectId: 'mymonshaa',
    storageBucket: 'mymonshaa.appspot.com',
    iosBundleId: 'com.example.ghhg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADvtqlQnKcSIlr_MK78dFS1QBEZS25dZ4',
    appId: '1:849173214576:ios:2ced1bc99a370e79874bb5',
    messagingSenderId: '849173214576',
    projectId: 'mymonshaa',
    storageBucket: 'mymonshaa.appspot.com',
    iosBundleId: 'com.example.ghhg.RunnerTests',
  );
}
